name: version_gen

description: The Dart code generator for your packages version.
version: 2.0.1
homepage: https://github.com/bf-tuyennv/version_gen
repository: https://github.com/bf-tuyennv/version_gen
documentation: https://github.com/bf-tuyennv/version_gen
issue_tracker: https://github.com/bf-tuyennv/version_gen/issues

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  build: ^3.0.0
  path: ^1.8.0
  yaml: ^3.0.0